import { WeddingData } from '../types';

export const initialWeddingData: WeddingData = {
  id: 'w-mampi-akash-2026',
  name: "Mampi's Wedding Budget",
  coupleNames: 'Mampi & Groom',
  date: '2026-11-28',
  totalBudget: 1100000,
  currency: 'INR',
  currencySymbol: '₹',
  city: 'Kolkata, West Bengal',
  events: [
    {
      id: 'evt-all',
      name: 'All Events Combined',
      date: '2026-11-28',
      allocatedBudget: 1100000,
      description: 'Overall wedding celebration and shopping budget',
    },
    {
      id: 'evt-shopping',
      name: 'Shopping, Tatta & Trousseau',
      date: '2026-11-15',
      allocatedBudget: 350000,
      description: 'Jewellery, Kolkata shopping, attire, and tatta gifts',
    },
    {
      id: 'evt-mehendi',
      name: 'Mehendi & Aiburobhat',
      date: '2026-11-26',
      allocatedBudget: 60000,
      description: 'Traditional feast, Mehendi artist, and pre-wedding styling',
    },
    {
      id: 'evt-wedding',
      name: 'Main Wedding (Biye)',
      date: '2026-11-28',
      allocatedBudget: 550000,
      description: 'Lodge, catering, photography, decoration, and mandap rituals',
    },
    {
      id: 'evt-reception',
      name: 'Boubhat & Reception',
      date: '2026-11-30',
      allocatedBudget: 140000,
      description: 'Formal reception dinner and family gathering',
    },
  ],
  categories: [
    { id: 'cat-jewellery', name: 'Jewellery & Gold', budget: 230000, icon: 'Gem', color: '#D97706' },
    { id: 'cat-catering', name: 'Catering & Feast', budget: 320000, icon: 'Utensils', color: '#C2410C' },
    { id: 'cat-venue', name: 'Venue & Lodge', budget: 90000, icon: 'Castle', color: '#B45309' },
    { id: 'cat-clothing', name: 'Clothing & Trousseau', budget: 60000, icon: 'Shirt', color: '#BE123C' },
    { id: 'cat-shopping', name: 'Kolkata Shopping & Cash', budget: 210000, icon: 'Gift', color: '#0D9488' },
    { id: 'cat-household', name: 'Furniture, TV & Watch', budget: 60000, icon: 'Layers', color: '#059669' },
    { id: 'cat-photo', name: 'Photography & Camera', budget: 35000, icon: 'Camera', color: '#2563EB' },
    { id: 'cat-makeup', name: 'Makeup & Styling', budget: 25000, icon: 'Palette', color: '#DB2777' },
    { id: 'cat-decor', name: 'Decoration & Music', budget: 25000, icon: 'Music', color: '#4F46E5' },
    { id: 'cat-accessories', name: 'Bridal Accessories', budget: 10000, icon: 'Sparkles', color: '#7C3AED' },
    { id: 'cat-rituals', name: 'Rituals & Ceremony', budget: 10000, icon: 'Flame', color: '#EA580C' },
  ],
  people: [
    { id: 'p-akash', name: 'Akash (Brother)', relation: 'Brother', avatarColor: '#80142B', phone: '+91 98301 23456' },
    { id: 'p-mampi', name: 'Mampi (Bride)', relation: 'Bride', avatarColor: '#DB2777', phone: '+91 98301 23457' },
    { id: 'p-dad', name: 'Dad (Father)', relation: 'Father', avatarColor: '#1E3A8A', phone: '+91 98301 23458' },
    { id: 'p-mom', name: 'Mom (Mother)', relation: 'Mother', avatarColor: '#C5A059', phone: '+91 98301 23459' },
    { id: 'p-family', name: 'Family & Relatives', relation: 'Family', avatarColor: '#059669', phone: '+91 98301 23460' },
  ],
  vendors: [
    {
      id: 'v-lodge',
      name: 'Wedding Lodge / Venue',
      category: 'Venue & Lodge',
      contractAmount: 80000,
      amountPaid: 5000,
      amountDue: 75000,
      contact: {
        phone: '+91 98300 11223',
        personName: 'Lodge Manager',
      },
      nextPaymentDate: '2026-11-20',
      notes: 'Total ₹80,000. Advance ₹5,000 deposited, balance ₹75,000 due before function.',
      status: 'Booked',
    },
    {
      id: 'v-catering',
      name: 'Wedding Caterer (Shahi Feast)',
      category: 'Catering & Feast',
      contractAmount: 300000,
      amountPaid: 100000,
      amountDue: 200000,
      contact: {
        phone: '+91 98300 22334',
        personName: 'Head Caterer',
      },
      nextPaymentDate: '2026-11-25',
      notes: 'Full catering service for wedding reception dinner (approx ₹3,00,000).',
      status: 'Booked',
    },
    {
      id: 'v-camera',
      name: 'Camera & Video Team',
      category: 'Photography & Camera',
      contractAmount: 28000,
      amountPaid: 5000,
      amountDue: 23000,
      contact: {
        phone: '+91 98300 33445',
        personName: 'Lead Photographer',
      },
      nextPaymentDate: '2026-11-22',
      notes: 'Full wedding event coverage. ₹5,000 advance paid, ₹23,000 due.',
      status: 'Booked',
    },
    {
      id: 'v-makeup',
      name: 'Bridal Makeup Artist',
      category: 'Makeup & Styling',
      contractAmount: 14000,
      amountPaid: 9000,
      amountDue: 5000,
      contact: {
        phone: '+91 98300 44556',
        personName: 'Bridal Stylist',
      },
      nextPaymentDate: '2026-11-28',
      notes: 'Bridal makeover. ₹9,000 paid, ₹5,000 remaining due on wedding day.',
      status: 'Booked',
    },
    {
      id: 'v-decor',
      name: 'Decoration & Floral Setup',
      category: 'Decoration & Music',
      contractAmount: 15000,
      amountPaid: 5000,
      amountDue: 10000,
      contact: {
        phone: '+91 98300 55667',
        personName: 'Decorator',
      },
      nextPaymentDate: '2026-11-27',
      notes: 'Lodge stage and entrance decoration (approx ₹15,000).',
      status: 'Booked',
    },
    {
      id: 'v-band',
      name: 'Wedding Band Party',
      category: 'Decoration & Music',
      contractAmount: 5000,
      amountPaid: 1000,
      amountDue: 4000,
      contact: {
        phone: '+91 98300 66778',
        personName: 'Band Master',
      },
      nextPaymentDate: '2026-11-28',
      notes: 'Procession music & lighting band (approx ₹5,000).',
      status: 'Booked',
    },
  ],
  expenses: [
    {
      id: 'exp-1',
      eventId: 'evt-shopping',
      categoryId: 'cat-jewellery',
      name: 'Gold Ring',
      amount: 57000,
      date: '2026-11-05',
      paidBy: 'Akash (Brother)',
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'Paid',
      notes: 'Gold ring : 57000/-',
      createdAt: '2026-11-05T10:00:00.000Z',
    },
    {
      id: 'exp-2',
      eventId: 'evt-shopping',
      categoryId: 'cat-jewellery',
      name: 'Gold Chain',
      amount: 161000,
      date: '2026-11-05',
      paidBy: 'Dad (Father)',
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'Paid',
      notes: 'Gold chain : 161000/-',
      createdAt: '2026-11-05T10:30:00.000Z',
    },
    {
      id: 'exp-3',
      eventId: 'evt-wedding',
      categoryId: 'cat-venue',
      vendorId: 'v-lodge',
      name: 'Lodge Booking',
      amount: 80000,
      totalAmount: 80000,
      amountPaid: 5000,
      amountRemaining: 75000,
      date: '2026-11-08',
      paidBy: 'Akash (Brother)',
      paymentMethod: 'UPI',
      paymentStatus: 'Partially Paid',
      notes: 'Lodge : 80000/-(5000/- advance paid)',
      createdAt: '2026-11-08T11:00:00.000Z',
    },
    {
      id: 'exp-4',
      eventId: 'evt-wedding',
      categoryId: 'cat-photo',
      vendorId: 'v-camera',
      name: 'Camera (Photography)',
      amount: 28000,
      totalAmount: 28000,
      amountPaid: 5000,
      amountRemaining: 23000,
      date: '2026-11-09',
      paidBy: 'Akash (Brother)',
      paymentMethod: 'UPI',
      paymentStatus: 'Partially Paid',
      notes: 'Camera : 28000/-(5000/- advance token paid)',
      createdAt: '2026-11-09T12:00:00.000Z',
    },
    {
      id: 'exp-5',
      eventId: 'evt-wedding',
      categoryId: 'cat-shopping',
      name: 'Cash Reserve / Shagun',
      amount: 150000,
      date: '2026-11-10',
      paidBy: 'Dad (Father)',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      notes: 'Cash : 150000/- (Liquid cash kept for wedding ceremonies & dakshina)',
      createdAt: '2026-11-10T14:00:00.000Z',
    },
    {
      id: 'exp-6',
      eventId: 'evt-shopping',
      categoryId: 'cat-clothing',
      name: '3 Piece Suit (+ Stitching)',
      amount: 11400,
      date: '2026-11-11',
      paidBy: 'Akash (Brother)',
      paymentMethod: 'Card',
      paymentStatus: 'Paid',
      notes: '3 piece suit : 7000/-(+4400/-stich) = ₹11,400',
      createdAt: '2026-11-11T15:00:00.000Z',
    },
    {
      id: 'exp-7',
      eventId: 'evt-shopping',
      categoryId: 'cat-accessories',
      name: 'Bag',
      amount: 1000,
      date: '2026-11-12',
      paidBy: 'Mampi (Bride)',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      notes: 'Bag - 1000/- (Bridal luggage / trousseau bag)',
      createdAt: '2026-11-12T10:00:00.000Z',
    },
    {
      id: 'exp-8',
      eventId: 'evt-wedding',
      categoryId: 'cat-rituals',
      name: 'Pirha (Ritual Piri)',
      amount: 600,
      date: '2026-11-12',
      paidBy: 'Akash (Brother)',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      notes: 'Pirha - 600/- (Ceremonial wooden piri for bridal Saat Paak)',
      createdAt: '2026-11-12T11:00:00.000Z',
    },
    {
      id: 'exp-9',
      eventId: 'evt-shopping',
      categoryId: 'cat-clothing',
      name: 'Saree Gift',
      amount: 6700,
      date: '2026-11-13',
      paidBy: 'Mom (Mother)',
      paymentMethod: 'Card',
      paymentStatus: 'Paid',
      notes: 'Saree gift - 6700/- (Gift sarees for family)',
      createdAt: '2026-11-13T16:00:00.000Z',
    },
    {
      id: 'exp-10',
      eventId: 'evt-shopping',
      categoryId: 'cat-jewellery',
      name: 'Bridal Jewellery (Fashion Set)',
      amount: 1500,
      date: '2026-11-13',
      paidBy: 'Mampi (Bride)',
      paymentMethod: 'UPI',
      paymentStatus: 'Paid',
      notes: 'Bridal jewellery - 1500/-',
      createdAt: '2026-11-13T17:00:00.000Z',
    },
    {
      id: 'exp-11',
      eventId: 'evt-shopping',
      categoryId: 'cat-clothing',
      name: 'Bridal Lehenga',
      amount: 20500,
      date: '2026-11-14',
      paidBy: 'Akash (Brother)',
      paymentMethod: 'Card',
      paymentStatus: 'Paid',
      notes: 'Lehenga - 20500/-',
      createdAt: '2026-11-14T12:00:00.000Z',
    },
    {
      id: 'exp-12',
      eventId: 'evt-shopping',
      categoryId: 'cat-accessories',
      name: 'Lehthi (Lac Bangles)',
      amount: 2200,
      date: '2026-11-14',
      paidBy: 'Mampi (Bride)',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      notes: 'Lehthi - 2200/- (Traditional bridal lac bangles)',
      createdAt: '2026-11-14T13:00:00.000Z',
    },
    {
      id: 'exp-13',
      eventId: 'evt-wedding',
      categoryId: 'cat-makeup',
      vendorId: 'v-makeup',
      name: 'Bridal Makeup',
      amount: 14000,
      totalAmount: 14000,
      amountPaid: 9000,
      amountRemaining: 5000,
      date: '2026-11-15',
      paidBy: 'Mampi (Bride)',
      paymentMethod: 'UPI',
      paymentStatus: 'Partially Paid',
      notes: 'Makeup - 14000/-(9000/- paid, ₹5,000 balance)',
      createdAt: '2026-11-15T14:00:00.000Z',
    },
    {
      id: 'exp-14',
      eventId: 'evt-mehendi',
      categoryId: 'cat-makeup',
      name: 'Mehendi',
      amount: 2000,
      date: '2026-11-15',
      paidBy: 'Mampi (Bride)',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      notes: 'Mehendi - 2000/-',
      createdAt: '2026-11-15T15:00:00.000Z',
    },
    {
      id: 'exp-15',
      eventId: 'evt-shopping',
      categoryId: 'cat-clothing',
      name: 'Chunri',
      amount: 4200,
      totalAmount: 4200,
      amountPaid: 1000,
      amountRemaining: 3200,
      date: '2026-11-16',
      paidBy: 'Akash (Brother)',
      paymentMethod: 'UPI',
      paymentStatus: 'Partially Paid',
      notes: 'Chunri - 4200/-(1000/- paid advance, ₹3,200 due)',
      createdAt: '2026-11-16T11:00:00.000Z',
    },
    {
      id: 'exp-16',
      eventId: 'evt-shopping',
      categoryId: 'cat-accessories',
      name: 'Kalira',
      amount: 250,
      date: '2026-11-16',
      paidBy: 'Mampi (Bride)',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      notes: 'Kalira - 250/- x (Purchased)',
      createdAt: '2026-11-16T11:30:00.000Z',
    },
    {
      id: 'exp-17',
      eventId: 'evt-shopping',
      categoryId: 'cat-accessories',
      name: 'Chura',
      amount: 380,
      date: '2026-11-16',
      paidBy: 'Mampi (Bride)',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      notes: 'Chura - 380/- x (Purchased)',
      createdAt: '2026-11-16T12:00:00.000Z',
    },
    {
      id: 'exp-18',
      eventId: 'evt-shopping',
      categoryId: 'cat-household',
      name: 'Furniture (approx)',
      amount: 15000,
      date: '2026-11-17',
      paidBy: 'Dad (Father)',
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'Paid',
      notes: 'Furniture - 15000/-(approx)',
      createdAt: '2026-11-17T10:00:00.000Z',
    },
    {
      id: 'exp-19',
      eventId: 'evt-shopping',
      categoryId: 'cat-household',
      name: 'TV (approx)',
      amount: 35000,
      date: '2026-11-17',
      paidBy: 'Akash (Brother)',
      paymentMethod: 'Card',
      paymentStatus: 'Paid',
      notes: 'TV - 35000/-(approx) Smart LED TV',
      createdAt: '2026-11-17T11:00:00.000Z',
    },
    {
      id: 'exp-20',
      eventId: 'evt-shopping',
      categoryId: 'cat-household',
      name: 'Watch (approx)',
      amount: 5000,
      date: '2026-11-18',
      paidBy: 'Akash (Brother)',
      paymentMethod: 'UPI',
      paymentStatus: 'Paid',
      notes: 'Watch - 5000/-(approx)',
      createdAt: '2026-11-18T10:00:00.000Z',
    },
    {
      id: 'exp-21',
      eventId: 'evt-wedding',
      categoryId: 'cat-catering',
      vendorId: 'v-catering',
      name: 'Catering (approx)',
      amount: 300000,
      totalAmount: 300000,
      amountPaid: 100000,
      amountRemaining: 200000,
      date: '2026-11-18',
      paidBy: 'Dad (Father)',
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'Partially Paid',
      notes: 'Catering - 300000/-(approx) (Advance ₹1,00,000 paid, ₹2,00,000 due)',
      createdAt: '2026-11-18T12:00:00.000Z',
    },
    {
      id: 'exp-22',
      eventId: 'evt-shopping',
      categoryId: 'cat-jewellery',
      name: 'Earring Fix (approx)',
      amount: 5000,
      date: '2026-11-19',
      paidBy: 'Mampi (Bride)',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      notes: 'Earring fix - 5000/-(approx) (Repair & polish)',
      createdAt: '2026-11-19T10:00:00.000Z',
    },
    {
      id: 'exp-23',
      eventId: 'evt-mehendi',
      categoryId: 'cat-makeup',
      name: 'Haath Phool Colour (approx)',
      amount: 600,
      date: '2026-11-19',
      paidBy: 'Mampi (Bride)',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      notes: 'Haath phool colour - 600/-(approx)',
      createdAt: '2026-11-19T11:00:00.000Z',
    },
    {
      id: 'exp-24',
      eventId: 'evt-shopping',
      categoryId: 'cat-clothing',
      name: 'Pant Shirt Gift (approx)',
      amount: 4000,
      date: '2026-11-20',
      paidBy: 'Akash (Brother)',
      paymentMethod: 'Card',
      paymentStatus: 'Paid',
      notes: 'Pant shirt gift - 4000/-(approx)',
      createdAt: '2026-11-20T14:00:00.000Z',
    },
    {
      id: 'exp-25',
      eventId: 'evt-shopping',
      categoryId: 'cat-shopping',
      name: 'Kolkata Shopping (approx)',
      amount: 50000,
      date: '2026-11-20',
      paidBy: 'Dad (Father)',
      paymentMethod: 'UPI',
      paymentStatus: 'Paid',
      notes: 'Kolkata shopping - 50000/-(approx) (Gariahat / Burrabazar market)',
      createdAt: '2026-11-20T15:00:00.000Z',
    },
    {
      id: 'exp-26',
      eventId: 'evt-wedding',
      categoryId: 'cat-decor',
      vendorId: 'v-band',
      name: 'Band (approx)',
      amount: 5000,
      date: '2026-11-21',
      paidBy: 'Akash (Brother)',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      notes: 'Band - 5000/-(approx) (Wedding band & procession)',
      createdAt: '2026-11-21T10:00:00.000Z',
    },
    {
      id: 'exp-27',
      eventId: 'evt-wedding',
      categoryId: 'cat-decor',
      vendorId: 'v-decor',
      name: 'Decoration (approx)',
      amount: 15000,
      date: '2026-11-21',
      paidBy: 'Akash (Brother)',
      paymentMethod: 'UPI',
      paymentStatus: 'Paid',
      notes: 'Decoration - 15000/-(approx) (Lodge & mandap decor)',
      createdAt: '2026-11-21T11:00:00.000Z',
    },
    {
      id: 'exp-28',
      eventId: 'evt-wedding',
      categoryId: 'cat-catering',
      name: 'Ranna (Cook / Catering Labor)',
      amount: 0,
      date: '2026-11-22',
      paidBy: 'Akash (Brother)',
      paymentMethod: 'Other',
      paymentStatus: 'Pending',
      notes: 'Ranna : (Cook / Halwai labor cost - estimate to be decided)',
      createdAt: '2026-11-22T09:00:00.000Z',
    },
    {
      id: 'exp-29',
      eventId: 'evt-mehendi',
      categoryId: 'cat-makeup',
      name: 'Makeup Kit',
      amount: 0,
      date: '2026-11-22',
      paidBy: 'Mampi (Bride)',
      paymentMethod: 'Other',
      paymentStatus: 'Pending',
      notes: 'Makeup kit : (Cosmetics & vanity box - estimate to be decided)',
      createdAt: '2026-11-22T09:30:00.000Z',
    },
    {
      id: 'exp-30',
      eventId: 'evt-shopping',
      categoryId: 'cat-clothing',
      name: 'Totto Kapor Cheler (approx)',
      amount: 5000,
      date: '2026-11-22',
      paidBy: 'Akash (Brother)',
      paymentMethod: 'Card',
      paymentStatus: 'Paid',
      notes: 'Totto kapor cheler : 5000/-(approx) (Groom side Tatta garments)',
      createdAt: '2026-11-22T10:00:00.000Z',
    },
  ],
  paymentSchedules: [
    {
      id: 'sch-1',
      vendorId: 'v-lodge',
      vendorName: 'Wedding Lodge / Venue',
      category: 'Venue & Lodge',
      amount: 75000,
      dueDate: '2026-11-20',
      status: 'Pending',
      notes: 'Remaining balance for lodge booking before event date.',
    },
    {
      id: 'sch-2',
      vendorId: 'v-camera',
      vendorName: 'Camera & Video Team',
      category: 'Photography & Camera',
      amount: 23000,
      dueDate: '2026-11-22',
      status: 'Pending',
      notes: 'Final camera crew & drone settlement balance.',
    },
    {
      id: 'sch-3',
      vendorId: 'v-catering',
      vendorName: 'Wedding Caterer (Shahi Feast)',
      category: 'Catering & Feast',
      amount: 200000,
      dueDate: '2026-11-25',
      status: 'Pending',
      notes: 'Final catering balance settlement after wedding feast.',
    },
    {
      id: 'sch-4',
      vendorId: 'v-makeup',
      vendorName: 'Bridal Makeup Artist',
      category: 'Makeup & Styling',
      amount: 5000,
      dueDate: '2026-11-28',
      status: 'Pending',
      notes: 'Balance to be cleared on wedding day makeup completion.',
    },
  ],
  settings: {
    useCompactINR: false,
    theme: 'light',
    activeEventId: 'all',
  },
};
