import { WeddingData } from '../types';

export const initialWeddingData: WeddingData = {
  id: 'w-akash-priya-2026',
  name: "Akash & Priya's Wedding",
  coupleNames: 'Akash & Priya',
  date: '2026-12-14',
  totalBudget: 1200000,
  currency: 'INR',
  currencySymbol: '₹',
  city: 'Jaipur / Delhi NCR',
  events: [
    {
      id: 'evt-all',
      name: 'All Events Combined',
      date: '2026-12-14',
      allocatedBudget: 1200000,
      description: 'Overall wedding celebration across all ceremonies',
    },
    {
      id: 'evt-ring',
      name: 'Ring Ceremony & Cocktail',
      date: '2026-12-12',
      allocatedBudget: 150000,
      description: 'Engagement rings exchange, music & cocktails',
    },
    {
      id: 'evt-mehendi',
      name: 'Mehendi & Sangeet',
      date: '2026-12-13',
      allocatedBudget: 250000,
      description: 'Henna ceremony, folk singing and dance performances',
    },
    {
      id: 'evt-wedding',
      name: 'Main Wedding (Baraat & Pheras)',
      date: '2026-12-14',
      allocatedBudget: 600000,
      description: 'Traditional Vedic rituals, Jaymala, and Mandap ceremony',
    },
    {
      id: 'evt-reception',
      name: 'Grand Reception',
      date: '2026-12-15',
      allocatedBudget: 200000,
      description: 'Formal family dinner and reception party',
    },
  ],
  categories: [
    { id: 'cat-venue', name: 'Venue', budget: 300000, icon: 'Castle', color: '#B45309' },
    { id: 'cat-catering', name: 'Catering', budget: 200000, icon: 'Utensils', color: '#C2410C' },
    { id: 'cat-decor', name: 'Decoration', budget: 100000, icon: 'Sparkles', color: '#7C3AED' },
    { id: 'cat-jewellery', name: 'Jewellery', budget: 150000, icon: 'Gem', color: '#D97706' },
    { id: 'cat-photo', name: 'Photography', budget: 80000, icon: 'Camera', color: '#2563EB' },
    { id: 'cat-clothing', name: 'Clothing', budget: 80000, icon: 'Shirt', color: '#BE123C' },
    { id: 'cat-makeup', name: 'Makeup & Mehendi', budget: 50000, icon: 'Palette', color: '#DB2777' },
    { id: 'cat-music', name: 'Entertainment & DJ', budget: 60000, icon: 'Music', color: '#4F46E5' },
    { id: 'cat-travel', name: 'Travel & Accom.', budget: 80000, icon: 'Car', color: '#059669' },
    { id: 'cat-invites', name: 'Invitations & Gifts', budget: 40000, icon: 'Gift', color: '#0891B2' },
    { id: 'cat-rituals', name: 'Rituals & Pandit', budget: 30000, icon: 'Flame', color: '#EA580C' },
    { id: 'cat-misc', name: 'Miscellaneous', budget: 30000, icon: 'Layers', color: '#64748B' },
  ],
  people: [
    { id: 'p-dad', name: 'Dad (Rajesh)', relation: 'Father of Groom', avatarColor: '#80142B', phone: '+91 98101 23456' },
    { id: 'p-mom', name: 'Mom (Sunita)', relation: 'Mother of Groom', avatarColor: '#C5A059', phone: '+91 98101 23457' },
    { id: 'p-akash', name: 'Akash (Groom)', relation: 'Groom', avatarColor: '#1E3A8A', phone: '+91 98101 23458' },
    { id: 'p-uncle', name: 'Chacha Ji (Ramesh)', relation: 'Uncle', avatarColor: '#065F46', phone: '+91 98101 23459' },
    { id: 'p-priya', name: 'Priya (Bride)', relation: 'Bride', avatarColor: '#9D174D', phone: '+91 98101 23460' },
    { id: 'p-brother', name: 'Rohan (Brother)', relation: 'Brother', avatarColor: '#5B21B6', phone: '+91 98101 23461' },
  ],
  vendors: [
    {
      id: 'v-palace',
      name: 'Royal Palace Banquet & Lawn',
      category: 'Venue',
      contractAmount: 300000,
      amountPaid: 200000,
      amountDue: 100000,
      contact: {
        phone: '+91 98765 43210',
        email: 'events@royalpalace.in',
        personName: 'Mr. Vikram Singh (Manager)',
      },
      nextPaymentDate: '2026-09-25',
      notes: 'Includes poolside lawn for Sangeet & main AC banquet for Wedding pheras.',
      status: 'Booked',
    },
    {
      id: 'v-shahi-caterers',
      name: 'Annapurna Shahi Caterers',
      category: 'Catering',
      contractAmount: 200000,
      amountPaid: 100000,
      amountDue: 100000,
      contact: {
        phone: '+91 98765 43211',
        email: 'info@annapurnacaterers.com',
        personName: 'Chef Harish Sharma',
      },
      nextPaymentDate: '2026-10-01',
      notes: 'Pure vegetarian royal buffet, live chaat counter, 8 desserts, 500 guests capacity.',
      status: 'Booked',
    },
    {
      id: 'v-decor',
      name: 'Utsav Floral & Theme Decor',
      category: 'Decoration',
      contractAmount: 100000,
      amountPaid: 65000,
      amountDue: 35000,
      contact: {
        phone: '+91 98765 43212',
        email: 'utsavdecor@gmail.com',
        personName: 'Anil Gupta',
      },
      nextPaymentDate: '2026-10-05',
      notes: 'Marigold entrance setup, glass mandap with fresh tuberoses & fairy canopy.',
      status: 'Booked',
    },
    {
      id: 'v-photo',
      name: 'Memories & Moments Studio',
      category: 'Photography',
      contractAmount: 80000,
      amountPaid: 30000,
      amountDue: 50000,
      contact: {
        phone: '+91 98765 43213',
        email: 'team@memoriesmoments.photo',
        personName: 'Kabir Verma (Lead Cinematographer)',
      },
      nextPaymentDate: '2026-09-25',
      notes: 'Drone coverage, 2 candid photographers, 1 cinematic teaser & wedding film.',
      status: 'Booked',
    },
    {
      id: 'v-clothing',
      name: 'Roopkala Bridal Couture',
      category: 'Clothing',
      contractAmount: 50000,
      amountPaid: 30000,
      amountDue: 20000,
      contact: {
        phone: '+91 98765 43214',
        personName: 'Smt. Shashi Mehra',
      },
      nextPaymentDate: '2026-10-15',
      notes: 'Custom bridal zardozi lehenga and groom raw silk sherwani fitting.',
      status: 'Booked',
    },
    {
      id: 'v-makeup',
      name: 'Glam Studio by Neha',
      category: 'Makeup & Mehendi',
      contractAmount: 35000,
      amountPaid: 15000,
      amountDue: 20000,
      contact: {
        phone: '+91 98765 43215',
        personName: 'Neha Kapoor',
      },
      nextPaymentDate: '2026-10-20',
      notes: 'Bridal airbrush makeup for Wedding day + subtle look for Sangeet.',
      status: 'Booked',
    },
  ],
  expenses: [
    {
      id: 'exp-1',
      eventId: 'evt-wedding',
      categoryId: 'cat-venue',
      vendorId: 'v-palace',
      name: 'Wedding Hall Advance Booking Token',
      amount: 45000,
      date: new Date().toISOString().split('T')[0], // Today
      paidBy: 'Dad (Rajesh)',
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'Paid',
      notes: '20% token transferred for blocking 14th Dec dates.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'exp-2',
      eventId: 'evt-wedding',
      categoryId: 'cat-clothing',
      vendorId: 'v-clothing',
      name: 'Bridal Lehenga Advance & Zari Work',
      amount: 18500,
      date: new Date(Date.now() - 86400000).toISOString().split('T')[0], // Yesterday
      paidBy: 'Mom (Sunita)',
      paymentMethod: 'Card',
      paymentStatus: 'Paid',
      notes: 'Initial deposit for custom hand-embroidered border.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'exp-3',
      eventId: 'evt-mehendi',
      categoryId: 'cat-photo',
      vendorId: 'v-photo',
      name: 'Photography Advance & Drone Token',
      amount: 25000,
      date: '2026-09-12',
      paidBy: 'Akash (Groom)',
      paymentMethod: 'UPI',
      paymentStatus: 'Paid',
      notes: 'GPay payment to Kabir Verma for team reservation.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'exp-4',
      eventId: 'evt-wedding',
      categoryId: 'cat-venue',
      vendorId: 'v-palace',
      name: 'Banquet Hall 1st Installment',
      amount: 155000,
      date: '2026-08-20',
      paidBy: 'Dad (Rajesh)',
      paymentMethod: 'Cheque',
      paymentStatus: 'Paid',
      notes: 'HDFC Bank cheque #40291 cleared.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'exp-5',
      eventId: 'evt-mehendi',
      categoryId: 'cat-venue',
      vendorId: 'v-palace',
      name: 'Poolside Lawn Lawn Security & Generator Fee',
      amount: 50000,
      date: '2026-08-28',
      paidBy: 'Chacha Ji (Ramesh)',
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'Paid',
      notes: 'Lawn lighting power backup and generator charges.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'exp-6',
      eventId: 'evt-wedding',
      categoryId: 'cat-catering',
      vendorId: 'v-shahi-caterers',
      name: 'Catering Menu Advance & Tasting Token',
      amount: 100000,
      date: '2026-08-15',
      paidBy: 'Dad (Rajesh)',
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'Paid',
      notes: '50% advance for raw ingredients and live kitchen stalls.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'exp-7',
      eventId: 'evt-reception',
      categoryId: 'cat-catering',
      vendorId: 'v-shahi-caterers',
      name: 'Reception Sweet Stalls & Mocktail Counter',
      amount: 80000,
      date: '2026-09-05',
      paidBy: 'Mom (Sunita)',
      paymentMethod: 'UPI',
      paymentStatus: 'Paid',
      notes: 'Special Rajasthani Ghevar and artisanal mocktail mixologist.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'exp-8',
      eventId: 'evt-wedding',
      categoryId: 'cat-decor',
      vendorId: 'v-decor',
      name: 'Floral Mandap & Entrance Gate Advance',
      amount: 65000,
      date: '2026-09-02',
      paidBy: 'Akash (Groom)',
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'Paid',
      notes: 'Exotic orchids and jasmine flowers reservation.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'exp-9',
      eventId: 'evt-mehendi',
      categoryId: 'cat-decor',
      vendorId: 'v-decor',
      name: 'Mehendi Swing & Quirky Photobooth Setup',
      amount: 20000,
      date: '2026-09-08',
      paidBy: 'Rohan (Brother)',
      paymentMethod: 'UPI',
      paymentStatus: 'Paid',
      notes: 'Marigold bangles, floral photo frame & neon signs.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'exp-10',
      eventId: 'evt-wedding',
      categoryId: 'cat-jewellery',
      name: 'Kundan Bridal Necklace & Polki Set',
      amount: 75000,
      date: '2026-08-10',
      paidBy: 'Mom (Sunita)',
      paymentMethod: 'Card',
      paymentStatus: 'Paid',
      notes: 'Tanishq jewellery purchase with hallmark certificate.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'exp-11',
      eventId: 'evt-ring',
      categoryId: 'cat-photo',
      vendorId: 'v-photo',
      name: 'Pre-wedding Shoot Day 1 Coverage',
      amount: 25000,
      date: '2026-09-01',
      paidBy: 'Akash (Groom)',
      paymentMethod: 'UPI',
      paymentStatus: 'Paid',
      notes: 'Location shoot at Neemrana Fort Palace.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'exp-12',
      eventId: 'evt-wedding',
      categoryId: 'cat-clothing',
      vendorId: 'v-clothing',
      name: 'Groom Silk Sherwani & Safa',
      amount: 24000,
      date: '2026-09-10',
      paidBy: 'Dad (Rajesh)',
      paymentMethod: 'Card',
      paymentStatus: 'Paid',
      notes: 'Manyavar sherwani with handcrafted royal safa & stole.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'exp-13',
      eventId: 'evt-mehendi',
      categoryId: 'cat-makeup',
      vendorId: 'v-makeup',
      name: 'Organic Rajasthani Henna Artist Team',
      amount: 15000,
      date: '2026-09-03',
      paidBy: 'Priya (Bride)',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      notes: 'Dark stain henna for bride and 20 close family ladies.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'exp-14',
      eventId: 'evt-wedding',
      categoryId: 'cat-makeup',
      vendorId: 'v-makeup',
      name: 'Bridal HD Makeup Advance',
      amount: 15000,
      date: '2026-09-06',
      paidBy: 'Priya (Bride)',
      paymentMethod: 'UPI',
      paymentStatus: 'Paid',
      notes: 'Trial completed and bridal slot confirmed.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'exp-15',
      eventId: 'evt-mehendi',
      categoryId: 'cat-music',
      name: 'DJ Console, Punjabi Dhol & Sound System',
      amount: 30000,
      date: '2026-09-04',
      paidBy: 'Chacha Ji (Ramesh)',
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      notes: 'Two live dhol players for baraat and sangeet night.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'exp-16',
      eventId: 'evt-mehendi',
      categoryId: 'cat-jewellery',
      name: 'Floral Jewellery for Haldi & Mehendi',
      amount: 17500,
      date: '2026-09-11',
      paidBy: 'Rohan (Brother)',
      paymentMethod: 'UPI',
      paymentStatus: 'Paid',
      notes: 'Fresh carnation and jasmine jewellery set for bride & sisters.',
      createdAt: new Date().toISOString(),
    },
  ],
  paymentSchedules: [
    {
      id: 'sch-1',
      vendorId: 'v-photo',
      vendorName: 'Memories & Moments Studio',
      category: 'Photography',
      amount: 50000,
      dueDate: '2026-09-25',
      status: 'Pending',
      notes: 'Pre-wedding edit release & main wedding full crew balance.',
    },
    {
      id: 'sch-2',
      vendorId: 'v-shahi-caterers',
      vendorName: 'Annapurna Shahi Caterers',
      category: 'Catering',
      amount: 100000,
      dueDate: '2026-10-01',
      status: 'Pending',
      notes: 'Second installment before finalizing dry-ration and dairy supply.',
    },
    {
      id: 'sch-3',
      vendorId: 'v-decor',
      vendorName: 'Utsav Floral & Theme Decor',
      category: 'Decoration',
      amount: 35000,
      dueDate: '2026-10-05',
      status: 'Pending',
      notes: 'Mandap structure fabrication balance.',
    },
    {
      id: 'sch-4',
      vendorId: 'v-palace',
      vendorName: 'Royal Palace Banquet & Lawn',
      category: 'Venue',
      amount: 30000,
      dueDate: '2026-11-12',
      status: 'Pending',
      notes: 'Pre-event final room booking and electricity deposit.',
    },
  ],
  settings: {
    useCompactINR: false,
    theme: 'light',
    activeEventId: 'all',
  },
};
